generation:
    provider: tgis # tgis or nlp
    service:
        hostname: localhost
        port: 8033
chunkers:
    en_regex:
        type: sentence
        service:
            hostname: localhost
            port: 8085
            tls: caikit
    en_syntax_izumo:
        type: sentence
        service:
            hostname: localhost
            port: 8085
            tls: caikit
detectors:
    hap-en:
        service:
            hostname: https://localhost/api/v1/detector
            port: 9000
            tls: caikit
        chunker_id: en_regex
        config: {}
tls:
    caikit:
        cert_path: /path/to/caikit/tls.crt
        key_path: /path/to/caikit/tls.key
        client_ca_cert_path: /path/to/caikit/ca.crt
